const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  personuuid: state => state.user.id,
  personcode: state => state.user.code,
  scenecode: state => state.user.scenecode,
  scenename: state => state.user.scenename,
  datauserid: state => state.user.datauserid,
  datausername: state => state.user.datausername,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  personIp: state => state.user.personIp,
  meauData: state => state.app.meauData,
  getToDoNum: state => state.aceState.toDoNum,
}
export default getters
